### ISSUE TITLE
Issue with HostB when running example code

### ISSUE THREAD

**Issue by dydx** [akoenig/kast#1]
Having a strange issue with running the example code, not sure whats the matter.

Running HostA everything appears OK. Running HostB, it exits unexpectedly with no errors displayed.

I also get no information back when running the client. I just get an empty `{}` back, even though HostA appears to be running OK.

Is there any extra setup required for doing the UDP broadcasts? I'm running Ubuntu 14.04 with Node 0.11.14

**Comment by akoenig** [comment]
Oh okay :) - An extra setup is not required. Is HostB running on a different box in your network?

**Comment by dydx** [comment]
Heya, I was out of town.

No, HostB is running on the same box. i have a feeling that might be the problem.

**Comment by akoenig** [comment]
Okay, this should be the problem. Try to run `HostB` on a different machine (e.g. VM) and it should work fine :)
